/**
 * A type of shape.
 */
export enum SHAPE {
    RECTANGLE,
    CIRCLE,
    TRIANGLE,
}

export enum GAMESTOPREASON {
    USER, // CODE 0; THE USER HAS STOPPED THE GAME.
    UNKNOWN, // CODE 1; ITS UNKNOWN WHAT CAUSED IT TO STOP.
    ERROR // CODE 2; AN ERROR HAS OCCURED, LOOK IN THE CONSOLE FOR MORE DATA.
}

export enum RENDERTYPE {
    IMAGE,
    BOLD
}