/**
 * A type of shape.
 */
export enum SHAPE {
    RECTANGLE,
    CIRCLE,
    TRIANGLE,
}

export enum GAMESTOPREASON {
    USER, // CODE 0; THE USER HAS STOPPED THE GAME.
    UNKNOWN, // CODE 1; ITS UNKNOWN WHAT CAUSED IT TO STOP.
    ERROR // CODE 2; AN ERROR HAS OCCURED, LOOK IN THE CONSOLE FOR MORE DATA.
}

export enum RENDERTYPE {
    IMAGE,
    BOLD
}

export enum KEYCODE {
    // KEYBOARD
    Q,W,E,R,T,Y,U,I,O,P,A,S,D,F,G,H,J,K,L,Z,X,C,V,B,N,M,
    ZERO,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,
    SPACE,LEFTSHIFT,RIGHTSHIFT,CAPSLOCK,TAB,ENTER,LEFTCTRL,RIGHTCTRL,BACKSPACE,PAUSE,ESCAPE,QUOTEDDOUBLE,HASH,DOLLAR,PERCENT,AMBERSAND,QUOTE,LEFTPARENTHESIS,
    RIGHTPARENTHESIS,ASTERISK,PLUS,COMMA,MINUS,PERIOD,SLASH,COLON,SEMICOLON,LESSTHAN,EQUALS,GREATERTHAN,QUESTION,AT,LEFTBRACKET,BACKSLASH,RIGHTBRACKET,CARET,UNDERSCORE,
    BACKQUOTE,LEFTCURLY,PIPE,RIGHTCURLY,TILDE,DELETE,KEYPADZERO,KEYPADONE,KEYPADTWO,KEYPADTHREE,KEYPADFOUR,KEYPADFIVE,KEYPADSIX,KEYPADSEVEN,KEYPADEIGHT,KEYPADNINE,
    KEYPADPERIOD,KEYPADDIVIDE,KEYPADMULTIPLY,KEYPADMINUS,KEYPADPLUS,KEYPADENTER,KEYPADEQUALS,INSERT,HOME,END,PAGEUP,PAGEDOWN,
    F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,
    NUMLOCK,SCROLLOCK,LEFTALT,RIGHTALT,RIGTHMETA,LEFTMETA,LEFTSUPER,RIGHTSUPER,MODE,COMPOSE,HELP,PRINT,SYSREQ,BREAK,MENU,POWER,EURO,UNDO,EXCLAMATION,
    LEFT,RIGHT,UP,DOWN,
    // CONTROLLER
    BUTTONY,BUTTONA,BUTTONX,BUTTONB,BUTTONR1,BUTTONL1,BUTTONR2,BUTTONL2,
    JOYSTICKLEFT,JOYSTICKRIGHT,
    DPADLEFT,DPADRIGHT,DPADUP,DPADDOWN,
    // MOUSE
    MOUSELEFT,MOUSERIGHT,MOUSEMIDDLE,
    WHEELUP, WHEELDOWN,
}